### ISSUE TITLE
Cannot install with composer

### ISSUE THREAD

**Issue by gertjanspriensma** [Convertio/convertio-php#6]
Hi guys, when I try to install this library with composer I get the following error;
"The requested package convertio/convertio-php could not be found in any version, there may be a typo in the package name.", which is not the case. Also when I try to install it with CLI I get a stability error, and even when set to "dev", it will not install.

**Comment by davidkryzaniak** [comment]
This repo is missing a composer.json file. So it cannot be installed via Composer.
