### ISSUE TITLE
Issue with startFromURL for google drive download URL

### ISSUE THREAD

**Issue by kane81** [Convertio/convertio-php#8]
I have the following URL which downloaded a word document which I want to convert to PDF
https://docs.google.com/uc?id=0BzY2TjE6XKcgU05CTmRuV18zbDQ&export=download

I have the following code

$API->startFromURL('https://docs.google.com/uc?id=0BzY2TjE6XKcgU05CTmRuV18zbDQ&export=download', 'PDF')->wait()->download('./output.pdf')->delete();

This code errors out 404
'The system is unable to find the requested action' in /home/pawsandc/public_html/pdf/src/API.php:170

if I change the url to say
$API->startFromURL('http://pawsclaws.org.au/pdf/Conrad.docx', 'PDF')->wait()->download('./output.pdf')->delete();

it works.

enter the google download URL on the website here works
https://convertio.co/document-converter/

so not sure why using the API does not work....

**Comment by Dantist** [comment]
Hi! Sorry for the huge delay with the reply, but better late than never!

1. We have **fixed an inappropriate exception** being thrown in this situation.
2. **This particular conversion issue has been fixed as well** (Technical details: in some situations our conversion hosts didn't handle chains of HTTP 302 redirects in URL correctly. Google Docs Export URL works this way, via HTTP 302 redirects).

**Thank you for reporting that.**

Please accept our apologies for the inconvenience we might have caused to you with these issues and the late reply!
