### ISSUE TITLE
Java api

### ISSUE THREAD

**Issue by shaohui93** [Convertio/convertio-php#9]
Hello, do you have a Java SDK or Java can only use REST API for document conversion?

**Comment by Dantist** [comment]
Hello!

Github Issues is not the best place for looking for support. Write to us at support@convertio.co.

Regarding your question:
1. We have only one official API wrapper at this moment: https://github.com/convertio/convertio-php.  
2. To use our API in your Java application you should write your own wrapper, implementing our REST API in it, following our simple [API reference](https://convertio.co/api/docs/). We will be happy if you can open-source your Java API wrapper in future. 

Please, accept our apologies for the inconvenience we might have caused to you with this.
